In [1]:
print("yyy_xyz_obs.ipynb")

yyy_xyz_obs.ipynb

In [2]:
#Libraries
import sys
sys.path.append("../2_depend") # go to parent dir
from libsy import *

In [3]:
xyz = pd.read_csv("../6_int/comb_pos_xyz.csv")
print("    in: "+"../6_int/comb_pos_xyz.csv")
xyz['desc'] = xyz['locus'] + "_" + xyz['genotype'] + "_" + xyz['exp.rep'].apply(str) + "_" + xyz['meiosis']
xyz['desk'] = xyz['desc'] + "_c" + xyz['cell'].apply(str)
xyz.head()

    in: ../6_int/comb_pos_xyz.csv

,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,foci,X1,Y1,Z1,X2,Y2,Z2,desc,desk
0,HET5,WT,2,t0,1,1,0,unp,16.0,24.0,31.0,21.0,15.0,31.0,HET5_WT_2_t0,HET5_WT_2_t0_c1
1,HET5,WT,2,t0,1,2,30,unp,19.0,15.0,31.0,19.0,25.0,31.0,HET5_WT_2_t0,HET5_WT_2_t0_c1
2,HET5,WT,2,t0,1,3,60,unp,20.0,18.0,30.0,15.0,25.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1
3,HET5,WT,2,t0,1,4,90,unp,21.0,19.0,30.0,14.0,22.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1
4,HET5,WT,2,t0,1,5,120,unp,22.0,18.0,30.0,15.0,24.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1

In [4]:
multifiles = glob.glob("../3_input/confy/*obs.xlsx")
multifiles = sorted(multifiles)
multifiles

['../3_input/confy/HET5WT2_t0_cells_obs.xlsx',
 '../3_input/confy/HET5WT2_t1_cells_obs.xlsx',
 '../3_input/confy/HET5WT2_t2_cells_obs.xlsx',
 '../3_input/confy/HET5WT2_t3_cells_obs.xlsx',
 '../3_input/confy/HET5WT2_t4_cells_obs.xlsx',
 '../3_input/confy/HET5WT2_t5_cells_obs.xlsx',
 '../3_input/confy/HET5WT3_t0_cells_obs.xlsx',
 '../3_input/confy/HET5WT3_t1_cells_obs.xlsx',
 '../3_input/confy/HET5WT3_t2_cells_obs.xlsx',
 '../3_input/confy/HET5WT3_t3_cells_obs.xlsx',
 '../3_input/confy/HET5WT3_t4_cells_obs.xlsx',
 '../3_input/confy/HET5WT3_t5_cells_obs.xlsx',
 '../3_input/confy/HET5WT3_ta_cells_obs.xlsx',
 '../3_input/confy/LYS2SP1_t0_cells_obs.xlsx',
 '../3_input/confy/LYS2SP1_t1_cells_obs.xlsx',
 '../3_input/confy/LYS2SP1_t2_cells_obs.xlsx',
 '../3_input/confy/LYS2SP1_t3_cells_obs.xlsx',
 '../3_input/confy/LYS2SP1_t4_cells_obs.xlsx',
 '../3_input/confy/LYS2SP1_t5_cells_obs.xlsx',
 '../3_input/confy/LYS2SP2_t0_cells_obs.xlsx',
 '../3_input/confy/LYS2SP2_t1_cells_obs.xlsx',
 '../3_input/confy/LYS2SP2_t2_cells_obs.xlsx',
 '../3_input/confy/LYS2SP2_t4_cells_obs.xlsx',
 '../3_input/confy/LYS2SP2_t5_cells_obs.xlsx',
 '../3_input/confy/LYS2SP2_t6_cells_obs.xlsx',
 '../3_input/confy/LYS2SP3_t0_cells_obs.xlsx',
 '../3_input/confy/LYS2SP3_t1_cells_obs.xlsx',
 '../3_input/confy/LYS2SP3_t2_cells_obs.xlsx',
 '../3_input/confy/LYS2SP3_t3_cells_obs.xlsx',
 '../3_input/confy/LYS2SP3_t4_cells_obs.xlsx',
 '../3_input/confy/LYS2SP3_t5_cells_obs.xlsx',
 '../3_input/confy/LYS2WT1_t0_cells_obs.xlsx',
 '../3_input/confy/LYS2WT1_t1_cells_obs.xlsx',
 '../3_input/confy/LYS2WT1_t2_cells_obs.xlsx',
 '../3_input/confy/LYS2WT1_t3_cells_obs.xlsx',
 '../3_input/confy/LYS2WT1_t4_cells_obs.xlsx',
 '../3_input/confy/LYS2WT1_t5_cells_obs.xlsx',
 '../3_input/confy/LYS2WT1_t6_cells_obs.xlsx',
 '../3_input/confy/LYS2WT2_t0_cells_obs.xlsx',
 '../3_input/confy/LYS2WT2_t1_cells_obs.xlsx',
 '../3_input/confy/LYS2WT2_t2_cells_obs.xlsx',
 '../3_input/confy/LYS2WT2_t3_cells_obs.xlsx',
 '../3_input/confy/LYS2WT2_t4_cells_obs.xlsx',
 '../3_input/confy/LYS2WT3_t0_cells_obs.xlsx',
 '../3_input/confy/LYS2WT3_t1_cells_obs.xlsx',
 '../3_input/confy/LYS2WT3_t2_cells_obs.xlsx',
 '../3_input/confy/LYS2WT3_t3_cells_obs.xlsx',
 '../3_input/confy/LYS2WT3_t5_cells_obs.xlsx',
 '../3_input/confy/URA3SP1_t0_cells_obs.xlsx',
 '../3_input/confy/URA3SP1_t1_cells_obs.xlsx',
 '../3_input/confy/URA3SP1_t2_cells_obs.xlsx',
 '../3_input/confy/URA3SP1_t3_cells_obs.xlsx',
 '../3_input/confy/URA3SP1_t4_cells_obs.xlsx',
 '../3_input/confy/URA3SP1_t5_cells_obs.xlsx',
 '../3_input/confy/URA3SP1_t6_cells_obs.xlsx',
 '../3_input/confy/URA3SP2_t0_cells_obs.xlsx',
 '../3_input/confy/URA3SP2_t1_cells_obs.xlsx',
 '../3_input/confy/URA3SP2_t3_cells_obs.xlsx',
 '../3_input/confy/URA3SP2_t4_cells_obs.xlsx',
 '../3_input/confy/URA3SP2_t5_cells_obs.xlsx',
 '../3_input/confy/URA3SP3_t0_cells_obs.xlsx',
 '../3_input/confy/URA3SP3_t1_cells_obs.xlsx',
 '../3_input/confy/URA3SP3_t3_cells_obs.xlsx',
 '../3_input/confy/URA3SP3_t4_cells_obs.xlsx',
 '../3_input/confy/URA3SP3_t5_cells_obs.xlsx',
 '../3_input/confy/URA3SP5_t0_cells_obs.xlsx',
 '../3_input/confy/URA3SP5_t1_cells_obs.xlsx',
 '../3_input/confy/URA3SP5_t2_cells_obs.xlsx',
 '../3_input/confy/URA3SP5_t3_cells_obs.xlsx',
 '../3_input/confy/URA3SP5_t4_cells_obs.xlsx',
 '../3_input/confy/URA3SP5_t5_cells_obs.xlsx',
 '../3_input/confy/URA3SP6_t0_cells_obs.xlsx',
 '../3_input/confy/URA3SP6_t1_cells_obs.xlsx',
 '../3_input/confy/URA3SP6_t3_cells_obs.xlsx',
 '../3_input/confy/URA3SP6_t4_cells_obs.xlsx',
 '../3_input/confy/URA3SP6_t5_cells_obs.xlsx',
 '../3_input/confy/URA3SP7_t0_cells_obs.xlsx',
 '../3_input/confy/URA3SP7_t1_cells_obs.xlsx',
 '../3_input/confy/URA3SP7_t2_cells_obs.xlsx',
 '../3_input/confy/URA3SP7_t3_cells_obs.xlsx',
 '../3_input/confy/URA3SP7_t4_cells_obs.xlsx',
 '../3_input/confy/URA3SP7_t5_cells_obs.xlsx',
 '../3_input/confy/URA3SP7_ta_cells_obs.xlsx',
 '../3_input/confy/URA3WT1_t0_cells_obs.xlsx',
 '../3_input/confy/URA3WT1_t1_cells_obs.xlsx',
 '../3_input/confy/URA3WT1_t2_cells_obs.xlsx',
 '../3_input/confy/URA3WT1_t3_cells_obs.xlsx',
 '../3_input/confy/URA3WT1_t5_cells_obs.xlsx',
 '../3_input/confy/URA3WT2_t1_cells_obs.xlsx',
 '../3_input/confy/URA3WT2_t2_cells_obs.xlsx',
 '../3_input/confy/URA3WT2_t3_cells_obs.xlsx',
 '../3_input/confy/URA3WT2_t4_cells_obs.xlsx',
 '../3_input/confy/URA3WT3_t0_cells_obs.xlsx',
 '../3_input/confy/URA3WT3_t1_cells_obs.xlsx',
 '../3_input/confy/URA3WT3_t3_cells_obs.xlsx',
 '../3_input/confy/URA3WT3_t4_cells_obs.xlsx',
 '../3_input/confy/URA3WT3_t5_cells_obs.xlsx',
 '../3_input/confy/URA3WT4_t0_cells_obs.xlsx',
 '../3_input/confy/URA3WT4_t1_cells_obs.xlsx',
 '../3_input/confy/URA3WT4_t2_cells_obs.xlsx',
 '../3_input/confy/URA3WT4_t3_cells_obs.xlsx',
 '../3_input/confy/URA3WT4_t4_cells_obs.xlsx',
 '../3_input/confy/URA3WT4_t5_cells_obs.xlsx',
 '../3_input/confy/URA3WT5_t0_cells_obs.xlsx',
 '../3_input/confy/URA3WT5_t1_cells_obs.xlsx',
 '../3_input/confy/URA3WT5_t2_cells_obs.xlsx',
 '../3_input/confy/URA3WT5_t3_cells_obs.xlsx',
 '../3_input/confy/URA3WT5_t4_cells_obs.xlsx',
 '../3_input/confy/URA3WT5_t5_cells_obs.xlsx',
 '../3_input/confy/URA3WT6_t0_cells_obs.xlsx',
 '../3_input/confy/URA3WT6_t1_cells_obs.xlsx',
 '../3_input/confy/URA3WT6_t3_cells_obs.xlsx',
 '../3_input/confy/URA3WT6_t4_cells_obs.xlsx',
 '../3_input/confy/URA3WT6_t5_cells_obs.xlsx',
 '../3_input/confy/URA3WT7_t0_cells_obs.xlsx',
 '../3_input/confy/URA3WT7_t1_cells_obs.xlsx',
 '../3_input/confy/URA3WT7_t2_cells_obs.xlsx',
 '../3_input/confy/URA3WT7_t3_cells_obs.xlsx',
 '../3_input/confy/URA3WT7_t4_cells_obs.xlsx',
 '../3_input/confy/URA3WT7_t5_cells_obs.xlsx',
 '../3_input/confy/URA3WT8_t0_cells_obs.xlsx',
 '../3_input/confy/URA3WT8_t1_cells_obs.xlsx',
 '../3_input/confy/URA3WT8_t2_cells_obs.xlsx',
 '../3_input/confy/URA3WT8_t3_cells_obs.xlsx',
 '../3_input/confy/URA3WT8_t4_cells_obs.xlsx',
 '../3_input/confy/URA3WT8_t5_cells_obs.xlsx',
 '../3_input/confy/URA3WT8_ta_cells_obs.xlsx',
 '../3_input/confy/URA3WT9_t0_cells_obs.xlsx',
 '../3_input/confy/URA3WT9_t1_cells_obs.xlsx',
 '../3_input/confy/URA3WT9_t2_cells_obs.xlsx',
 '../3_input/confy/URA3WT9_t3_cells_obs.xlsx',
 '../3_input/confy/URA3WT9_t4_cells_obs.xlsx',
 '../3_input/confy/URA3WT9_ta_cells_obs.xlsx']

In [5]:
mcall = []
for file in multifiles:
    dffy = pd.read_excel(file, sep=",")
    print("    in: "+file)
    mcall.append(dffy)
mcall = pd.concat(mcall)

    in: ../3_input/confy/HET5WT2_t0_cells_obs.xlsx
    in: ../3_input/confy/HET5WT2_t1_cells_obs.xlsx
    in: ../3_input/confy/HET5WT2_t2_cells_obs.xlsx
    in: ../3_input/confy/HET5WT2_t3_cells_obs.xlsx
    in: ../3_input/confy/HET5WT2_t4_cells_obs.xlsx
    in: ../3_input/confy/HET5WT2_t5_cells_obs.xlsx
    in: ../3_input/confy/HET5WT3_t0_cells_obs.xlsx
    in: ../3_input/confy/HET5WT3_t1_cells_obs.xlsx
    in: ../3_input/confy/HET5WT3_t2_cells_obs.xlsx
    in: ../3_input/confy/HET5WT3_t3_cells_obs.xlsx
    in: ../3_input/confy/HET5WT3_t4_cells_obs.xlsx
    in: ../3_input/confy/HET5WT3_t5_cells_obs.xlsx
    in: ../3_input/confy/HET5WT3_ta_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP1_t0_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP1_t1_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP1_t2_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP1_t3_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP1_t4_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP1_t5_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP2_t0_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP2_t1_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP2_t2_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP2_t4_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP2_t5_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP2_t6_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP3_t0_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP3_t1_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP3_t2_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP3_t3_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP3_t4_cells_obs.xlsx
    in: ../3_input/confy/LYS2SP3_t5_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT1_t0_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT1_t1_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT1_t2_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT1_t3_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT1_t4_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT1_t5_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT1_t6_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT2_t0_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT2_t1_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT2_t2_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT2_t3_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT2_t4_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT3_t0_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT3_t1_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT3_t2_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT3_t3_cells_obs.xlsx
    in: ../3_input/confy/LYS2WT3_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3SP1_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3SP1_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3SP1_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3SP1_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3SP1_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3SP1_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3SP1_t6_cells_obs.xlsx
    in: ../3_input/confy/URA3SP2_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3SP2_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3SP2_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3SP2_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3SP2_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3SP3_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3SP3_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3SP3_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3SP3_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3SP3_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3SP5_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3SP5_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3SP5_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3SP5_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3SP5_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3SP5_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3SP6_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3SP6_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3SP6_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3SP6_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3SP6_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3SP7_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3SP7_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3SP7_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3SP7_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3SP7_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3SP7_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3SP7_ta_cells_obs.xlsx
    in: ../3_input/confy/URA3WT1_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3WT1_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3WT1_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3WT1_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3WT1_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3WT2_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3WT2_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3WT2_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3WT2_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3WT3_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3WT3_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3WT3_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3WT3_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3WT3_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3WT4_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3WT4_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3WT4_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3WT4_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3WT4_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3WT4_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3WT5_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3WT5_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3WT5_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3WT5_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3WT5_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3WT5_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3WT6_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3WT6_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3WT6_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3WT6_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3WT6_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3WT7_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3WT7_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3WT7_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3WT7_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3WT7_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3WT7_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3WT8_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3WT8_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3WT8_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3WT8_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3WT8_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3WT8_t5_cells_obs.xlsx
    in: ../3_input/confy/URA3WT8_ta_cells_obs.xlsx
    in: ../3_input/confy/URA3WT9_t0_cells_obs.xlsx
    in: ../3_input/confy/URA3WT9_t1_cells_obs.xlsx
    in: ../3_input/confy/URA3WT9_t2_cells_obs.xlsx
    in: ../3_input/confy/URA3WT9_t3_cells_obs.xlsx
    in: ../3_input/confy/URA3WT9_t4_cells_obs.xlsx
    in: ../3_input/confy/URA3WT9_ta_cells_obs.xlsx

In [6]:
obsy = mcall
obsy = obsy[obsy['Strain'].notnull()]
obsy = obsy[obsy['Strain'] != ""]
obsy.to_csv("../6_int/comb_obs.csv", sep=',', index=False)
print("    out: "+"../6_int/comb_obs.csv")
obsy.head()

    out: ../6_int/comb_obs.csv

,Strain,Cond,Exp,t,Cell,Observations,No,Area,StdDev,Perim,EllipseMajor,EllipseMinor,EllipseAngle,IntDen,RawInDen,num,X,Y
0,HET5,WT,2,0,1,Okay,1,5.400000e-08,20.581704,0.001274,0.000321,0.000216,12.837688,0.000014,77520,1,313.735779,814.762543
1,HET5,WT,2,0,2,Two cells,2,1.800000e-08,25.248762,0.000631,0.000166,0.000139,61.193936,0.000005,25755,2,257.276489,778.833893
2,HET5,WT,2,0,3,Two cells,3,3.600000e-08,55.583237,0.001005,0.000283,0.000161,5.803937,0.000009,48705,3,308.603119,726.224091
3,HET5,WT,2,0,4,Two cells,4,1.500000e-08,0.000000,0.000556,0.000161,0.000115,132.722145,0.000004,20910,4,372.761414,667.198441
4,HET5,WT,2,0,5,Two cells,5,1.800000e-08,50.221328,0.000738,0.000173,0.000131,84.415505,0.000004,24480,5,353.513916,642.818298

In [7]:
obs = pd.read_csv("../6_int/comb_obs.csv")
print("    in: "+"../6_int/comb_obs.csv")
obs['t'] = "t" + obs['t'].apply(str)
obs['desc'] = obs['Strain'] + "_" + obs['Cond'] + "_" + obs['Exp'].apply(str) + "_" + obs['t']
obs['desk'] = obs['desc'] + "_c" + obs['Cell'].apply(str)
obs = obs.sort_values(by=['Strain', 'Cond', 'Exp', 't', 'Cell'])
obs.head()

    in: ../6_int/comb_obs.csv

,Strain,Cond,Exp,t,Cell,Observations,No,Area,StdDev,Perim,EllipseMajor,EllipseMinor,EllipseAngle,IntDen,RawInDen,num,X,Y,desc,desk
0,HET5,WT,2,t0,1,Okay,1,5.400000e-08,20.581704,0.001274,0.000321,0.000216,12.837688,0.000014,77520,1,313.735779,814.762543,HET5_WT_2_t0,HET5_WT_2_t0_c1
1,HET5,WT,2,t0,2,Two cells,2,1.800000e-08,25.248762,0.000631,0.000166,0.000139,61.193936,0.000005,25755,2,257.276489,778.833893,HET5_WT_2_t0,HET5_WT_2_t0_c2
2,HET5,WT,2,t0,3,Two cells,3,3.600000e-08,55.583237,0.001005,0.000283,0.000161,5.803937,0.000009,48705,3,308.603119,726.224091,HET5_WT_2_t0,HET5_WT_2_t0_c3
3,HET5,WT,2,t0,4,Two cells,4,1.500000e-08,0.000000,0.000556,0.000161,0.000115,132.722145,0.000004,20910,4,372.761414,667.198441,HET5_WT_2_t0,HET5_WT_2_t0_c4
4,HET5,WT,2,t0,5,Two cells,5,1.800000e-08,50.221328,0.000738,0.000173,0.000131,84.415505,0.000004,24480,5,353.513916,642.818298,HET5_WT_2_t0,HET5_WT_2_t0_c5

In [8]:
ob = pd.DataFrame({"desk":obs['desk'], "Observations":obs['Observations']})
ob.head()

  Observations             desk
0         Okay  HET5_WT_2_t0_c1
1    Two cells  HET5_WT_2_t0_c2
2    Two cells  HET5_WT_2_t0_c3
3    Two cells  HET5_WT_2_t0_c4
4    Two cells  HET5_WT_2_t0_c5

In [9]:
xyz.head()

,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,foci,X1,Y1,Z1,X2,Y2,Z2,desc,desk
0,HET5,WT,2,t0,1,1,0,unp,16.0,24.0,31.0,21.0,15.0,31.0,HET5_WT_2_t0,HET5_WT_2_t0_c1
1,HET5,WT,2,t0,1,2,30,unp,19.0,15.0,31.0,19.0,25.0,31.0,HET5_WT_2_t0,HET5_WT_2_t0_c1
2,HET5,WT,2,t0,1,3,60,unp,20.0,18.0,30.0,15.0,25.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1
3,HET5,WT,2,t0,1,4,90,unp,21.0,19.0,30.0,14.0,22.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1
4,HET5,WT,2,t0,1,5,120,unp,22.0,18.0,30.0,15.0,24.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1

In [10]:
xyzobs = pd.merge(xyz, ob, on=['desk'], how='inner')
xyzobs = xyzobs.rename(columns={"Observations": "observation"})
xyzobs.to_csv("../6_int/xyz_pos_obs.csv", sep=',', index=False)
print("    out: "+"../6_int/xyz_pos_obs.csv")
xyzobs.head()

    out: ../6_int/xyz_pos_obs.csv

,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,foci,X1,Y1,Z1,X2,Y2,Z2,desc,desk,observation
0,HET5,WT,2,t0,1,1,0,unp,16.0,24.0,31.0,21.0,15.0,31.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay
1,HET5,WT,2,t0,1,2,30,unp,19.0,15.0,31.0,19.0,25.0,31.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay
2,HET5,WT,2,t0,1,3,60,unp,20.0,18.0,30.0,15.0,25.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay
3,HET5,WT,2,t0,1,4,90,unp,21.0,19.0,30.0,14.0,22.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay
4,HET5,WT,2,t0,1,5,120,unp,22.0,18.0,30.0,15.0,24.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay