In [1]:
print("zzz_xyz_confhack.ipynb")

zzz_xyz_confhack.ipynb

In [2]:
#Libraries
import sys
sys.path.append("../2_depend") # go to parent dir
from libsy import *

In [3]:
xyz = pd.read_csv("../6_int/xyz_pos_obs.csv")
print("    in: "+"../6_int/xyz_pos_obs.csv")
xyz.head()

    in: ../6_int/xyz_pos_obs.csv

,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,foci,X1,Y1,Z1,X2,Y2,Z2,desc,desk,observation
0,HET5,WT,2,t0,1,1,0,unp,16.0,24.0,31.0,21.0,15.0,31.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay
1,HET5,WT,2,t0,1,2,30,unp,19.0,15.0,31.0,19.0,25.0,31.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay
2,HET5,WT,2,t0,1,3,60,unp,20.0,18.0,30.0,15.0,25.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay
3,HET5,WT,2,t0,1,4,90,unp,21.0,19.0,30.0,14.0,22.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay
4,HET5,WT,2,t0,1,5,120,unp,22.0,18.0,30.0,15.0,24.0,34.0,HET5_WT_2_t0,HET5_WT_2_t0_c1,Okay

In [4]:
multiplefiles = glob.glob("../3_input/confy/*dist.csv")
multiplefiles = sorted(multiplefiles)
multiplefiles

['../3_input/confy/HET5WT2_t0_conf_dist.csv',
 '../3_input/confy/HET5WT2_t1_conf_dist.csv',
 '../3_input/confy/HET5WT2_t2_conf_dist.csv',
 '../3_input/confy/HET5WT2_t3_conf_dist.csv',
 '../3_input/confy/HET5WT2_t4_conf_dist.csv',
 '../3_input/confy/HET5WT2_t5_conf_dist.csv',
 '../3_input/confy/HET5WT3_t0_conf_dist.csv',
 '../3_input/confy/HET5WT3_t1_conf_dist.csv',
 '../3_input/confy/HET5WT3_t2_conf_dist.csv',
 '../3_input/confy/HET5WT3_t3_conf_dist.csv',
 '../3_input/confy/HET5WT3_t4_conf_dist.csv',
 '../3_input/confy/HET5WT3_t5_conf_dist.csv',
 '../3_input/confy/HET5WT3_ta_conf_dist.csv',
 '../3_input/confy/LYS2SP1_t0_conf_dist.csv',
 '../3_input/confy/LYS2SP1_t1_conf_dist.csv',
 '../3_input/confy/LYS2SP1_t2_conf_dist.csv',
 '../3_input/confy/LYS2SP1_t3_conf_dist.csv',
 '../3_input/confy/LYS2SP1_t4_conf_dist.csv',
 '../3_input/confy/LYS2SP1_t5_conf_dist.csv',
 '../3_input/confy/LYS2SP2_t0_conf_dist.csv',
 '../3_input/confy/LYS2SP2_t1_conf_dist.csv',
 '../3_input/confy/LYS2SP2_t2_conf_dist.csv',
 '../3_input/confy/LYS2SP2_t4_conf_dist.csv',
 '../3_input/confy/LYS2SP2_t5_conf_dist.csv',
 '../3_input/confy/LYS2SP2_t6_conf_dist.csv',
 '../3_input/confy/LYS2SP3_t0_conf_dist.csv',
 '../3_input/confy/LYS2SP3_t1_conf_dist.csv',
 '../3_input/confy/LYS2SP3_t2_conf_dist.csv',
 '../3_input/confy/LYS2SP3_t3_conf_dist.csv',
 '../3_input/confy/LYS2SP3_t4_conf_dist.csv',
 '../3_input/confy/LYS2SP3_t5_conf_dist.csv',
 '../3_input/confy/LYS2WT1_t0_conf_dist.csv',
 '../3_input/confy/LYS2WT1_t1_conf_dist.csv',
 '../3_input/confy/LYS2WT1_t2_conf_dist.csv',
 '../3_input/confy/LYS2WT1_t3_conf_dist.csv',
 '../3_input/confy/LYS2WT1_t4_conf_dist.csv',
 '../3_input/confy/LYS2WT1_t5_conf_dist.csv',
 '../3_input/confy/LYS2WT1_t6_conf_dist.csv',
 '../3_input/confy/LYS2WT2_t0_conf_dist.csv',
 '../3_input/confy/LYS2WT2_t1_conf_dist.csv',
 '../3_input/confy/LYS2WT2_t2_conf_dist.csv',
 '../3_input/confy/LYS2WT2_t3_conf_dist.csv',
 '../3_input/confy/LYS2WT2_t4_conf_dist.csv',
 '../3_input/confy/LYS2WT3_t0_conf_dist.csv',
 '../3_input/confy/LYS2WT3_t1_conf_dist.csv',
 '../3_input/confy/LYS2WT3_t2_conf_dist.csv',
 '../3_input/confy/LYS2WT3_t3_conf_dist.csv',
 '../3_input/confy/LYS2WT3_t5_conf_dist.csv',
 '../3_input/confy/URA3SP1_t0_conf_dist.csv',
 '../3_input/confy/URA3SP1_t1_conf_dist.csv',
 '../3_input/confy/URA3SP1_t2_conf_dist.csv',
 '../3_input/confy/URA3SP1_t3_conf_dist.csv',
 '../3_input/confy/URA3SP1_t4_conf_dist.csv',
 '../3_input/confy/URA3SP1_t5_conf_dist.csv',
 '../3_input/confy/URA3SP1_t6_conf_dist.csv',
 '../3_input/confy/URA3SP2_t0_conf_dist.csv',
 '../3_input/confy/URA3SP2_t1_conf_dist.csv',
 '../3_input/confy/URA3SP2_t3_conf_dist.csv',
 '../3_input/confy/URA3SP2_t4_conf_dist.csv',
 '../3_input/confy/URA3SP2_t5_conf_dist.csv',
 '../3_input/confy/URA3SP3_t0_conf_dist.csv',
 '../3_input/confy/URA3SP3_t1_conf_dist.csv',
 '../3_input/confy/URA3SP3_t3_conf_dist.csv',
 '../3_input/confy/URA3SP3_t4_conf_dist.csv',
 '../3_input/confy/URA3SP3_t5_conf_dist.csv',
 '../3_input/confy/URA3SP5_t0_conf_dist.csv',
 '../3_input/confy/URA3SP5_t1_conf_dist.csv',
 '../3_input/confy/URA3SP5_t2_conf_dist.csv',
 '../3_input/confy/URA3SP5_t3_conf_dist.csv',
 '../3_input/confy/URA3SP5_t4_conf_dist.csv',
 '../3_input/confy/URA3SP5_t5_conf_dist.csv',
 '../3_input/confy/URA3SP6_t0_conf_dist.csv',
 '../3_input/confy/URA3SP6_t1_conf_dist.csv',
 '../3_input/confy/URA3SP6_t3_conf_dist.csv',
 '../3_input/confy/URA3SP6_t4_conf_dist.csv',
 '../3_input/confy/URA3SP6_t5_conf_dist.csv',
 '../3_input/confy/URA3SP7_t0_conf_dist.csv',
 '../3_input/confy/URA3SP7_t1_conf_dist.csv',
 '../3_input/confy/URA3SP7_t2_conf_dist.csv',
 '../3_input/confy/URA3SP7_t3_conf_dist.csv',
 '../3_input/confy/URA3SP7_t4_conf_dist.csv',
 '../3_input/confy/URA3SP7_t5_conf_dist.csv',
 '../3_input/confy/URA3SP7_ta_conf_dist.csv',
 '../3_input/confy/URA3WT1_t0_conf_dist.csv',
 '../3_input/confy/URA3WT1_t1_conf_dist.csv',
 '../3_input/confy/URA3WT1_t2_conf_dist.csv',
 '../3_input/confy/URA3WT1_t3_conf_dist.csv',
 '../3_input/confy/URA3WT1_t5_conf_dist.csv',
 '../3_input/confy/URA3WT2_t1_conf_dist.csv',
 '../3_input/confy/URA3WT2_t2_conf_dist.csv',
 '../3_input/confy/URA3WT2_t3_conf_dist.csv',
 '../3_input/confy/URA3WT2_t4_conf_dist.csv',
 '../3_input/confy/URA3WT3_t0_conf_dist.csv',
 '../3_input/confy/URA3WT3_t1_conf_dist.csv',
 '../3_input/confy/URA3WT3_t3_conf_dist.csv',
 '../3_input/confy/URA3WT3_t4_conf_dist.csv',
 '../3_input/confy/URA3WT3_t5_conf_dist.csv',
 '../3_input/confy/URA3WT4_t0_conf_dist.csv',
 '../3_input/confy/URA3WT4_t1_conf_dist.csv',
 '../3_input/confy/URA3WT4_t2_conf_dist.csv',
 '../3_input/confy/URA3WT4_t3_conf_dist.csv',
 '../3_input/confy/URA3WT4_t4_conf_dist.csv',
 '../3_input/confy/URA3WT4_t5_conf_dist.csv',
 '../3_input/confy/URA3WT5_t0_conf_dist.csv',
 '../3_input/confy/URA3WT5_t1_conf_dist.csv',
 '../3_input/confy/URA3WT5_t2_conf_dist.csv',
 '../3_input/confy/URA3WT5_t3_conf_dist.csv',
 '../3_input/confy/URA3WT5_t4_conf_dist.csv',
 '../3_input/confy/URA3WT5_t5_conf_dist.csv',
 '../3_input/confy/URA3WT6_t0_conf_dist.csv',
 '../3_input/confy/URA3WT6_t1_conf_dist.csv',
 '../3_input/confy/URA3WT6_t3_conf_dist.csv',
 '../3_input/confy/URA3WT6_t4_conf_dist.csv',
 '../3_input/confy/URA3WT6_t5_conf_dist.csv',
 '../3_input/confy/URA3WT7_t0_conf_dist.csv',
 '../3_input/confy/URA3WT7_t1_conf_dist.csv',
 '../3_input/confy/URA3WT7_t2_conf_dist.csv',
 '../3_input/confy/URA3WT7_t3_conf_dist.csv',
 '../3_input/confy/URA3WT7_t4_conf_dist.csv',
 '../3_input/confy/URA3WT7_t5_conf_dist.csv',
 '../3_input/confy/URA3WT8_t0_conf_dist.csv',
 '../3_input/confy/URA3WT8_t1_conf_dist.csv',
 '../3_input/confy/URA3WT8_t2_conf_dist.csv',
 '../3_input/confy/URA3WT8_t3_conf_dist.csv',
 '../3_input/confy/URA3WT8_t4_conf_dist.csv',
 '../3_input/confy/URA3WT8_t5_conf_dist.csv',
 '../3_input/confy/URA3WT8_ta_conf_dist.csv',
 '../3_input/confy/URA3WT9_t0_conf_dist.csv',
 '../3_input/confy/URA3WT9_t1_conf_dist.csv',
 '../3_input/confy/URA3WT9_t2_conf_dist.csv',
 '../3_input/confy/URA3WT9_t3_conf_dist.csv',
 '../3_input/confy/URA3WT9_t4_conf_dist.csv',
 '../3_input/confy/URA3WT9_ta_conf_dist.csv']

In [5]:
conffy = []
for file in multiplefiles:
    dffy = pd.read_csv(file, sep=",", header=None)
    print("    in: "+file)
    ff = file
    ff = ff.replace("_conf_dist.csv","")
    ff = ff.replace("../3_input/confy/","")
    ff = ff.replace("_","")
    mdffy = pd.melt(dffy)
    mdffy['file'] = ff
    mdffy['deskc'] = mdffy['file'] + "_c" + mdffy['variable'].apply(str)
    # get index of timepoints
    mmm = []
    for m in mdffy['deskc'].unique():
        md = mdffy[mdffy['deskc'] == m]
        md = md.reset_index()
        md = md.drop(columns="index")
        md = md.reset_index()
        mmm.append(md)
    mmm = pd.concat(mmm)
    conffy.append(mmm)
conffy = pd.concat(conffy)
conffy['deskct'] = conffy['deskc'] + "_t" + conffy['index'].apply(str)
conffy = conffy.drop(columns=["index", "variable", "file", "deskc"])

    in: ../3_input/confy/HET5WT2_t0_conf_dist.csv
    in: ../3_input/confy/HET5WT2_t1_conf_dist.csv
    in: ../3_input/confy/HET5WT2_t2_conf_dist.csv
    in: ../3_input/confy/HET5WT2_t3_conf_dist.csv
    in: ../3_input/confy/HET5WT2_t4_conf_dist.csv
    in: ../3_input/confy/HET5WT2_t5_conf_dist.csv
    in: ../3_input/confy/HET5WT3_t0_conf_dist.csv
    in: ../3_input/confy/HET5WT3_t1_conf_dist.csv
    in: ../3_input/confy/HET5WT3_t2_conf_dist.csv
    in: ../3_input/confy/HET5WT3_t3_conf_dist.csv
    in: ../3_input/confy/HET5WT3_t4_conf_dist.csv
    in: ../3_input/confy/HET5WT3_t5_conf_dist.csv
    in: ../3_input/confy/HET5WT3_ta_conf_dist.csv
    in: ../3_input/confy/LYS2SP1_t0_conf_dist.csv
    in: ../3_input/confy/LYS2SP1_t1_conf_dist.csv
    in: ../3_input/confy/LYS2SP1_t2_conf_dist.csv
    in: ../3_input/confy/LYS2SP1_t3_conf_dist.csv
    in: ../3_input/confy/LYS2SP1_t4_conf_dist.csv
    in: ../3_input/confy/LYS2SP1_t5_conf_dist.csv
    in: ../3_input/confy/LYS2SP2_t0_conf_dist.csv
    in: ../3_input/confy/LYS2SP2_t1_conf_dist.csv
    in: ../3_input/confy/LYS2SP2_t2_conf_dist.csv
    in: ../3_input/confy/LYS2SP2_t4_conf_dist.csv
    in: ../3_input/confy/LYS2SP2_t5_conf_dist.csv
    in: ../3_input/confy/LYS2SP2_t6_conf_dist.csv
    in: ../3_input/confy/LYS2SP3_t0_conf_dist.csv
    in: ../3_input/confy/LYS2SP3_t1_conf_dist.csv
    in: ../3_input/confy/LYS2SP3_t2_conf_dist.csv
    in: ../3_input/confy/LYS2SP3_t3_conf_dist.csv
    in: ../3_input/confy/LYS2SP3_t4_conf_dist.csv
    in: ../3_input/confy/LYS2SP3_t5_conf_dist.csv
    in: ../3_input/confy/LYS2WT1_t0_conf_dist.csv
    in: ../3_input/confy/LYS2WT1_t1_conf_dist.csv
    in: ../3_input/confy/LYS2WT1_t2_conf_dist.csv
    in: ../3_input/confy/LYS2WT1_t3_conf_dist.csv
    in: ../3_input/confy/LYS2WT1_t4_conf_dist.csv
    in: ../3_input/confy/LYS2WT1_t5_conf_dist.csv
    in: ../3_input/confy/LYS2WT1_t6_conf_dist.csv
    in: ../3_input/confy/LYS2WT2_t0_conf_dist.csv
    in: ../3_input/confy/LYS2WT2_t1_conf_dist.csv
    in: ../3_input/confy/LYS2WT2_t2_conf_dist.csv
    in: ../3_input/confy/LYS2WT2_t3_conf_dist.csv
    in: ../3_input/confy/LYS2WT2_t4_conf_dist.csv
    in: ../3_input/confy/LYS2WT3_t0_conf_dist.csv
    in: ../3_input/confy/LYS2WT3_t1_conf_dist.csv
    in: ../3_input/confy/LYS2WT3_t2_conf_dist.csv
    in: ../3_input/confy/LYS2WT3_t3_conf_dist.csv
    in: ../3_input/confy/LYS2WT3_t5_conf_dist.csv
    in: ../3_input/confy/URA3SP1_t0_conf_dist.csv
    in: ../3_input/confy/URA3SP1_t1_conf_dist.csv
    in: ../3_input/confy/URA3SP1_t2_conf_dist.csv
    in: ../3_input/confy/URA3SP1_t3_conf_dist.csv
    in: ../3_input/confy/URA3SP1_t4_conf_dist.csv
    in: ../3_input/confy/URA3SP1_t5_conf_dist.csv
    in: ../3_input/confy/URA3SP1_t6_conf_dist.csv
    in: ../3_input/confy/URA3SP2_t0_conf_dist.csv
    in: ../3_input/confy/URA3SP2_t1_conf_dist.csv
    in: ../3_input/confy/URA3SP2_t3_conf_dist.csv
    in: ../3_input/confy/URA3SP2_t4_conf_dist.csv
    in: ../3_input/confy/URA3SP2_t5_conf_dist.csv
    in: ../3_input/confy/URA3SP3_t0_conf_dist.csv
    in: ../3_input/confy/URA3SP3_t1_conf_dist.csv
    in: ../3_input/confy/URA3SP3_t3_conf_dist.csv
    in: ../3_input/confy/URA3SP3_t4_conf_dist.csv
    in: ../3_input/confy/URA3SP3_t5_conf_dist.csv
    in: ../3_input/confy/URA3SP5_t0_conf_dist.csv
    in: ../3_input/confy/URA3SP5_t1_conf_dist.csv
    in: ../3_input/confy/URA3SP5_t2_conf_dist.csv
    in: ../3_input/confy/URA3SP5_t3_conf_dist.csv
    in: ../3_input/confy/URA3SP5_t4_conf_dist.csv
    in: ../3_input/confy/URA3SP5_t5_conf_dist.csv
    in: ../3_input/confy/URA3SP6_t0_conf_dist.csv
    in: ../3_input/confy/URA3SP6_t1_conf_dist.csv
    in: ../3_input/confy/URA3SP6_t3_conf_dist.csv
    in: ../3_input/confy/URA3SP6_t4_conf_dist.csv
    in: ../3_input/confy/URA3SP6_t5_conf_dist.csv
    in: ../3_input/confy/URA3SP7_t0_conf_dist.csv
    in: ../3_input/confy/URA3SP7_t1_conf_dist.csv
    in: ../3_input/confy/URA3SP7_t2_conf_dist.csv
    in: ../3_input/confy/URA3SP7_t3_conf_dist.csv
    in: ../3_input/confy/URA3SP7_t4_conf_dist.csv
    in: ../3_input/confy/URA3SP7_t5_conf_dist.csv
    in: ../3_input/confy/URA3SP7_ta_conf_dist.csv
    in: ../3_input/confy/URA3WT1_t0_conf_dist.csv
    in: ../3_input/confy/URA3WT1_t1_conf_dist.csv
    in: ../3_input/confy/URA3WT1_t2_conf_dist.csv
    in: ../3_input/confy/URA3WT1_t3_conf_dist.csv
    in: ../3_input/confy/URA3WT1_t5_conf_dist.csv
    in: ../3_input/confy/URA3WT2_t1_conf_dist.csv
    in: ../3_input/confy/URA3WT2_t2_conf_dist.csv
    in: ../3_input/confy/URA3WT2_t3_conf_dist.csv
    in: ../3_input/confy/URA3WT2_t4_conf_dist.csv
    in: ../3_input/confy/URA3WT3_t0_conf_dist.csv
    in: ../3_input/confy/URA3WT3_t1_conf_dist.csv
    in: ../3_input/confy/URA3WT3_t3_conf_dist.csv
    in: ../3_input/confy/URA3WT3_t4_conf_dist.csv
    in: ../3_input/confy/URA3WT3_t5_conf_dist.csv
    in: ../3_input/confy/URA3WT4_t0_conf_dist.csv
    in: ../3_input/confy/URA3WT4_t1_conf_dist.csv
    in: ../3_input/confy/URA3WT4_t2_conf_dist.csv
    in: ../3_input/confy/URA3WT4_t3_conf_dist.csv
    in: ../3_input/confy/URA3WT4_t4_conf_dist.csv
    in: ../3_input/confy/URA3WT4_t5_conf_dist.csv
    in: ../3_input/confy/URA3WT5_t0_conf_dist.csv
    in: ../3_input/confy/URA3WT5_t1_conf_dist.csv
    in: ../3_input/confy/URA3WT5_t2_conf_dist.csv
    in: ../3_input/confy/URA3WT5_t3_conf_dist.csv
    in: ../3_input/confy/URA3WT5_t4_conf_dist.csv
    in: ../3_input/confy/URA3WT5_t5_conf_dist.csv
    in: ../3_input/confy/URA3WT6_t0_conf_dist.csv
    in: ../3_input/confy/URA3WT6_t1_conf_dist.csv
    in: ../3_input/confy/URA3WT6_t3_conf_dist.csv
    in: ../3_input/confy/URA3WT6_t4_conf_dist.csv
    in: ../3_input/confy/URA3WT6_t5_conf_dist.csv
    in: ../3_input/confy/URA3WT7_t0_conf_dist.csv
    in: ../3_input/confy/URA3WT7_t1_conf_dist.csv
    in: ../3_input/confy/URA3WT7_t2_conf_dist.csv
    in: ../3_input/confy/URA3WT7_t3_conf_dist.csv
    in: ../3_input/confy/URA3WT7_t4_conf_dist.csv
    in: ../3_input/confy/URA3WT7_t5_conf_dist.csv
    in: ../3_input/confy/URA3WT8_t0_conf_dist.csv
    in: ../3_input/confy/URA3WT8_t1_conf_dist.csv
    in: ../3_input/confy/URA3WT8_t2_conf_dist.csv
    in: ../3_input/confy/URA3WT8_t3_conf_dist.csv
    in: ../3_input/confy/URA3WT8_t4_conf_dist.csv
    in: ../3_input/confy/URA3WT8_t5_conf_dist.csv
    in: ../3_input/confy/URA3WT8_ta_conf_dist.csv
    in: ../3_input/confy/URA3WT9_t0_conf_dist.csv
    in: ../3_input/confy/URA3WT9_t1_conf_dist.csv
    in: ../3_input/confy/URA3WT9_t2_conf_dist.csv
    in: ../3_input/confy/URA3WT9_t3_conf_dist.csv
    in: ../3_input/confy/URA3WT9_t4_conf_dist.csv
    in: ../3_input/confy/URA3WT9_ta_conf_dist.csv

In [6]:
conffy.head()

    value           deskct
0  1.3693  HET5WT2t0_c0_t0
1  1.3300  HET5WT2t0_c0_t1
2  1.5195  HET5WT2t0_c0_t2
3  1.4234  HET5WT2t0_c0_t3
4  1.5823  HET5WT2t0_c0_t4

In [7]:
xyz_d = xyz
xyz_d['desk'] = xyz_d['locus'] + xyz_d['genotype'] + xyz_d['exp.rep'].apply(str) + xyz_d['meiosis']
xyz_d['deskc'] = xyz_d['desk'] + "_c" + (xyz_d['cell']-1).apply(str)
xyz_d['deskct'] = xyz_d['deskc'] + "_t" + (xyz_d['tp.n']-1).apply(str)
xyz_d.head()

,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,foci,X1,Y1,Z1,X2,Y2,Z2,desc,desk,observation,deskc,deskct
0,HET5,WT,2,t0,1,1,0,unp,16.0,24.0,31.0,21.0,15.0,31.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t0
1,HET5,WT,2,t0,1,2,30,unp,19.0,15.0,31.0,19.0,25.0,31.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t1
2,HET5,WT,2,t0,1,3,60,unp,20.0,18.0,30.0,15.0,25.0,34.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t2
3,HET5,WT,2,t0,1,4,90,unp,21.0,19.0,30.0,14.0,22.0,34.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t3
4,HET5,WT,2,t0,1,5,120,unp,22.0,18.0,30.0,15.0,24.0,34.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t4

In [8]:
conffy.head()

    value           deskct
0  1.3693  HET5WT2t0_c0_t0
1  1.3300  HET5WT2t0_c0_t1
2  1.5195  HET5WT2t0_c0_t2
3  1.4234  HET5WT2t0_c0_t3
4  1.5823  HET5WT2t0_c0_t4

In [9]:
xyz_d.head()

,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,foci,X1,Y1,Z1,X2,Y2,Z2,desc,desk,observation,deskc,deskct
0,HET5,WT,2,t0,1,1,0,unp,16.0,24.0,31.0,21.0,15.0,31.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t0
1,HET5,WT,2,t0,1,2,30,unp,19.0,15.0,31.0,19.0,25.0,31.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t1
2,HET5,WT,2,t0,1,3,60,unp,20.0,18.0,30.0,15.0,25.0,34.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t2
3,HET5,WT,2,t0,1,4,90,unp,21.0,19.0,30.0,14.0,22.0,34.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t3
4,HET5,WT,2,t0,1,5,120,unp,22.0,18.0,30.0,15.0,24.0,34.0,HET5_WT_2_t0,HET5WT2t0,Okay,HET5WT2t0_c0,HET5WT2t0_c0_t4

In [10]:
mrr = pd.merge(xyz_d, conffy, on=['deskct'], how='inner')
mrr = mrr.drop(columns=["desk", "deskc"])
mrr = mrr.rename(columns={"value": "confdist"})
mrr = mrr.sort_values(by=['locus', 'genotype', 'exp.rep', 'meiosis', 'cell', 'tp.n'])
mrr.head()

,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,foci,X1,Y1,Z1,X2,Y2,Z2,desc,observation,deskct,confdist
0,HET5,WT,2,t0,1,1,0,unp,16.0,24.0,31.0,21.0,15.0,31.0,HET5_WT_2_t0,Okay,HET5WT2t0_c0_t0,1.3693
1,HET5,WT,2,t0,1,2,30,unp,19.0,15.0,31.0,19.0,25.0,31.0,HET5_WT_2_t0,Okay,HET5WT2t0_c0_t1,1.3300
2,HET5,WT,2,t0,1,3,60,unp,20.0,18.0,30.0,15.0,25.0,34.0,HET5_WT_2_t0,Okay,HET5WT2t0_c0_t2,1.5195
3,HET5,WT,2,t0,1,4,90,unp,21.0,19.0,30.0,14.0,22.0,34.0,HET5_WT_2_t0,Okay,HET5WT2t0_c0_t3,1.4234
4,HET5,WT,2,t0,1,5,120,unp,22.0,18.0,30.0,15.0,24.0,34.0,HET5_WT_2_t0,Okay,HET5WT2t0_c0_t4,1.5823

In [11]:
# experiment removal
rem = pd.read_csv("../3_input/remove.csv")
print("    in: "+"../3_input/remove.csv")
mrr['desk'] = mrr['locus'] + "_" + mrr['genotype'] + "_" + mrr['exp.rep'].apply(str) + "_" + mrr['meiosis']
rmrr = mrr[-mrr['desk'].isin(rem['exp'])]
rmrr = rmrr.drop(columns=["deskct"])
rmrr.to_csv("../6_int/xyz_confhack_pre-exp.csv", sep='\t', index=False)
print("    out: "+"../6_int/xyz_confhack_pre-exp.csv")
rmrr.head()

    in: ../3_input/remove.csv
    out: ../6_int/xyz_confhack_pre-exp.csv

,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,foci,X1,Y1,Z1,X2,Y2,Z2,desc,observation,confdist,desk
0,HET5,WT,2,t0,1,1,0,unp,16.0,24.0,31.0,21.0,15.0,31.0,HET5_WT_2_t0,Okay,1.3693,HET5_WT_2_t0
1,HET5,WT,2,t0,1,2,30,unp,19.0,15.0,31.0,19.0,25.0,31.0,HET5_WT_2_t0,Okay,1.3300,HET5_WT_2_t0
2,HET5,WT,2,t0,1,3,60,unp,20.0,18.0,30.0,15.0,25.0,34.0,HET5_WT_2_t0,Okay,1.5195,HET5_WT_2_t0
3,HET5,WT,2,t0,1,4,90,unp,21.0,19.0,30.0,14.0,22.0,34.0,HET5_WT_2_t0,Okay,1.4234,HET5_WT_2_t0
4,HET5,WT,2,t0,1,5,120,unp,22.0,18.0,30.0,15.0,24.0,34.0,HET5_WT_2_t0,Okay,1.5823,HET5_WT_2_t0

In [12]:
crmrr = rmrr
crmrr = crmrr.reset_index()
crmrr = crmrr.drop(columns=["index"])
crmrr = crmrr.reset_index()

start1 = time.time()

nac = crmrr
nac['X1'] = np.where(nac['confdist'].isnull(), float('nan'), nac['X1'])
nac['Y1'] = np.where(nac['confdist'].isnull(), float('nan'), nac['Y1'])
nac['Z1'] = np.where(nac['confdist'].isnull(), float('nan'), nac['Z1'])
nac['X2'] = np.where(nac['confdist'].isnull(), float('nan'), nac['X2'])
nac['Y2'] = np.where(nac['confdist'].isnull(), float('nan'), nac['Y2'])
nac['Z2'] = np.where(nac['confdist'].isnull(), float('nan'), nac['Z2'])

nac['X1'] = nac['X1']*0.1
nac['Y1'] = nac['Y1']*0.1
nac['Z1'] = nac['Z1']*0.1
nac['X2'] = nac['X2']*0.1
nac['Y2'] = nac['Y2']*0.1
nac['Z2'] = nac['Z2']*0.1

nxyz = nac

end1 = time.time()
print("time:")
print(end1 - start1)

time:
0.029071569442749023

In [13]:
nxyz.to_csv("../6_int/xyz_confhack_post-exp.csv", sep='\t', index=False)
print("    out: "+"../6_int/xyz_confhack_post-exp.csv")
nxyz.head()

    out: ../6_int/xyz_confhack_post-exp.csv

,index,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,foci,X1,Y1,Z1,X2,Y2,Z2,desc,observation,confdist,desk
0,0,HET5,WT,2,t0,1,1,0,unp,1.6,2.4,3.1,2.1,1.5,3.1,HET5_WT_2_t0,Okay,1.3693,HET5_WT_2_t0
1,1,HET5,WT,2,t0,1,2,30,unp,1.9,1.5,3.1,1.9,2.5,3.1,HET5_WT_2_t0,Okay,1.3300,HET5_WT_2_t0
2,2,HET5,WT,2,t0,1,3,60,unp,2.0,1.8,3.0,1.5,2.5,3.4,HET5_WT_2_t0,Okay,1.5195,HET5_WT_2_t0
3,3,HET5,WT,2,t0,1,4,90,unp,2.1,1.9,3.0,1.4,2.2,3.4,HET5_WT_2_t0,Okay,1.4234,HET5_WT_2_t0
4,4,HET5,WT,2,t0,1,5,120,unp,2.2,1.8,3.0,1.5,2.4,3.4,HET5_WT_2_t0,Okay,1.5823,HET5_WT_2_t0

In [14]:
ok = ["Okay", "Oay", "okay", "Okat"]
onxyz = nxyz[nxyz['observation'].isin(ok)]
onxyz = onxyz.drop(columns=['index', 'foci', 'desc', 'confdist'])
onxyz.to_csv("../7_out/xyz_conf_okaycells-exp2.csv", sep=',', index=False)
print("    out: "+"../7_out/xyz_conf_okaycells-exp2.csv")
onxyz.head()

    out: ../7_out/xyz_conf_okaycells-exp2.csv

,locus,genotype,exp.rep,meiosis,cell,tp.n,tp.s,X1,Y1,Z1,X2,Y2,Z2,observation,desk
0,HET5,WT,2,t0,1,1,0,1.6,2.4,3.1,2.1,1.5,3.1,Okay,HET5_WT_2_t0
1,HET5,WT,2,t0,1,2,30,1.9,1.5,3.1,1.9,2.5,3.1,Okay,HET5_WT_2_t0
2,HET5,WT,2,t0,1,3,60,2.0,1.8,3.0,1.5,2.5,3.4,Okay,HET5_WT_2_t0
3,HET5,WT,2,t0,1,4,90,2.1,1.9,3.0,1.4,2.2,3.4,Okay,HET5_WT_2_t0
4,HET5,WT,2,t0,1,5,120,2.2,1.8,3.0,1.5,2.4,3.4,Okay,HET5_WT_2_t0